### ISSUE TITLE
la vm non parte

### ISSUE THREAD

**Issue by sabbio93** [sabbio93/jujuBundles#2]
#1 semra risolto con l'ip su eno2 presente solo su neutron-gateway.
funziona:

-caricamento immagini

- creazione volumi

- creazione liste
non funziona lo startup delle VM
Nota: la vm prende due indirizzi sulla rete privata :-o

**Comment by sabbio93** [comment]
On Nova scheduler in nova cloud controller 
2018-03-19 10:08:14.238 61198 ERROR nova.scheduler.utils [req-eb3279fb-e6a8-4a05-b0b9-18842faa5515 10f61b13406d4dbd87d67a3411e44245 1f92dea66cc54b46a56dea495a9ca991 - b1e1653f4a7a4755bb075c6ee9d65f48 b1e1653f4a7a4755bb075c6ee9d65f48] [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b] Error from last host: hardy-snake (node hardy-snake): [u'Traceback (most recent call last):\n', u'  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 1840, in _do_build_and_run_instance\n    filter_properties, request_spec)\n', u'  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 2108, in _build_and_run_instance\n    instance_uuid=instance.uuid, reason=six.text_type(e))\n', u"RescheduledException: Build of instance 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b was re-scheduled: internal error: qemu unexpectedly closed the monitor: 2018-03-19T10:08:10.304526Z qemu-system-x86_64: -drive file=rbd:cinder-ceph/volume-e296b267-18f4-473a-9d8f-b659a0b49474:id=cinder-ceph:auth_supported=cephx\\;none:mon_host=192.168.211.10\\:6789\\;192.168.211.201\\:6789\\;192.168.211.202\\:6789,file.password-secret=virtio-disk0-secret0,format=raw,if=none,id=drive-virtio-disk0,serial=e296b267-18f4-473a-9d8f-b659a0b49474,cache=none,discard=unmap: 'serial' is deprecated, please use the corresponding option of '-device' instead\nCould not read keymap file: 'it-it'\n"]

**Comment by sabbio93** [comment]
==> nova-conductor.log <==
2018-03-19 10:08:44.276 61197 ERROR nova.scheduler.utils [req-eb3279fb-e6a8-4a05-b0b9-18842faa5515 10f61b13406d4dbd87d67a3411e44245 1f92dea66cc54b46a56dea495a9ca991 - b1e1653f4a7a4755bb075c6ee9d65f48 b1e1653f4a7a4755bb075c6ee9d65f48] [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b] Error from last host: top-lizard (node top-lizard): [u'Traceback (most recent call last):\n', u'  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 1840, in _do_build_and_run_instance\n    filter_properties, request_spec)\n', u'  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 2108, in _build_and_run_instance\n    instance_uuid=instance.uuid, reason=six.text_type(e))\n', u"RescheduledException: Build of instance 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b was re-scheduled: internal error: qemu unexpectedly closed the monitor: 2018-03-19T10:08:39.684804Z qemu-system-x86_64: -drive file=rbd:cinder-ceph/volume-e296b267-18f4-473a-9d8f-b659a0b49474:id=cinder-ceph:auth_supported=cephx\\;none:mon_host=192.168.211.10\\:6789\\;192.168.211.201\\:6789\\;192.168.211.202\\:6789,file.password-secret=virtio-disk0-secret0,format=raw,if=none,id=drive-virtio-disk0,serial=e296b267-18f4-473a-9d8f-b659a0b49474,cache=none,discard=unmap: 'serial' is deprecated, please use the corresponding option of '-device' instead\nCould not read keymap file: 'it-it'\n"]
2018-03-19 10:08:44.277 61197 WARNING nova.scheduler.utils [req-eb3279fb-e6a8-4a05-b0b9-18842faa5515 10f61b13406d4dbd87d67a3411e44245 1f92dea66cc54b46a56dea495a9ca991 - b1e1653f4a7a4755bb075c6ee9d65f48 b1e1653f4a7a4755bb075c6ee9d65f48] Failed to compute_task_build_instances: Exceeded maximum number of retries. Exceeded max scheduling attempts 3 for instance 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b. Last exception: internal error: qemu unexpectedly closed the monitor: 2018-03-19T10:08:39.684804Z qemu-system-x86_64: -drive file=rbd:cinder-ceph/volume-e296b267-18f4-473a-9d8f-b659a0b49474:id=cinder-ceph:auth_supported=cephx\;none:mon_host=192.168.211.10\:6789\;192.168.211.201\:6789\;192.168.211.202\:6789,file.password-secret=virtio-disk0-secret0,format=raw,if=none,id=drive-virtio-disk0,serial=e296b267-18f4-473a-9d8f-b659a0b49474,cache=none,discard=unmap: 'serial' is deprecated, please use the corresponding option of '-device' instead
Could not read keymap file: 'it-it': MaxRetriesExceeded: Exceeded maximum number of retries. Exceeded max scheduling attempts 3 for instance 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b. Last exception: internal error: qemu unexpectedly closed the monitor: 2018-03-19T10:08:39.684804Z qemu-system-x86_64: -drive file=rbd:cinder-ceph/volume-e296b267-18f4-473a-9d8f-b659a0b49474:id=cinder-ceph:auth_supported=cephx\;none:mon_host=192.168.211.10\:6789\;192.168.211.201\:6789\;192.168.211.202\:6789,file.password-secret=virtio-disk0-secret0,format=raw,if=none,id=drive-virtio-disk0,serial=e296b267-18f4-473a-9d8f-b659a0b49474,cache=none,discard=unmap: 'serial' is deprecated, please use the corresponding option of '-device' instead
2018-03-19 10:08:44.277 61197 WARNING nova.scheduler.utils [req-eb3279fb-e6a8-4a05-b0b9-18842faa5515 10f61b13406d4dbd87d67a3411e44245 1f92dea66cc54b46a56dea495a9ca991 - b1e1653f4a7a4755bb075c6ee9d65f48 b1e1653f4a7a4755bb075c6ee9d65f48] [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b] Setting instance to ERROR state.: MaxRetriesExceeded: Exceeded maximum number of retries. Exceeded max scheduling attempts 3 for instance 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b. Last exception: internal error: qemu unexpectedly closed the monitor: 2018-03-19T10:08:39.684804Z qemu-system-x86_64: -drive file=rbd:cinder-ceph/volume-e296b267-18f4-473a-9d8f-b659a0b49474:id=cinder-ceph:auth_supported=cephx\;none:mon_host=192.168.211.10\:6789\;192.168.211.201\:6789\;192.168.211.202\:6789,file.password-secret=virtio-disk0-secret0,format=raw,if=none,id=drive-virtio-disk0,serial=e296b267-18f4-473a-9d8f-b659a0b49474,cache=none,discard=unmap: 'serial' is deprecated, please use the corresponding option of '-device' instead
2018-03-19 10:08:44.672 61197 ERROR nova.conductor.manager [req-d4a866c7-a627-46a3-a214-7760f0100972 - - - - -] [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b] Failed to deallocate networks: NoSuchOptError: no such option keystone_authtoken in group [DEFAULT]
2018-03-19 10:08:44.672 61197 ERROR nova.conductor.manager [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b] Traceback (most recent call last):
2018-03-19 10:08:44.672 61197 ERROR nova.conductor.manager [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b]   File "/usr/lib/python2.7/dist-packages/nova/conductor/manager.py", line 366, in _cleanup_allocated_networks
2018-03-19 10:08:44.672 61197 ERROR nova.conductor.manager [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b]     context, instance, requested_networks=requested_networks)
2018-03-19 10:08:44.672 61197 ERROR nova.conductor.manager [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b]   File "/usr/lib/python2.7/dist-packages/nova/network/neutronv2/api.py", line 1270, in deallocate_for_instance
2018-03-19 10:08:44.672 61197 ERROR nova.conductor.manager [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b]     self._unbind_ports(context, ports_to_skip, neutron)
2018-03-19 10:08:44.672 61197 ERROR nova.conductor.manager [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b]   File "/usr/lib/python2.7/dist-packages/nova/network/neutronv2/api.py", line 527, in _unbind_ports
2018-03-19 10:08:44.672 61197 ERROR nova.conductor.manager [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b]     port_client = get_client(context, admin=True)
2018-03-19 10:08:44.672 61197 ERROR nova.conductor.manager [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b]   File "/usr/lib/python2.7/dist-packages/nova/network/neutronv2/api.py", line 153, in get_client
2018-03-19 10:08:44.672 61197 ERROR nova.conductor.manager [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b]     _ADMIN_AUTH = _load_auth_plugin(CONF)
2018-03-19 10:08:44.672 61197 ERROR nova.conductor.manager [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b]   File "/usr/lib/python2.7/dist-packages/nova/network/neutronv2/api.py", line 70, in _load_auth_plugin
2018-03-19 10:08:44.672 61197 ERROR nova.conductor.manager [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b]     nova.conf.neutron.NEUTRON_GROUP)
2018-03-19 10:08:44.672 61197 ERROR nova.conductor.manager [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b]   File "/usr/lib/python2.7/dist-packages/keystoneauth1/loading/conf.py", line 122, in load_from_conf_options
2018-03-19 10:08:44.672 61197 ERROR nova.conductor.manager [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b]     name = conf[group].auth_type
2018-03-19 10:08:44.672 61197 ERROR nova.conductor.manager [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b]   File "/usr/lib/python2.7/dist-packages/oslo_config/cfg.py", line 2523, in __getitem__
2018-03-19 10:08:44.672 61197 ERROR nova.conductor.manager [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b]     return self.__getattr__(key)
2018-03-19 10:08:44.672 61197 ERROR nova.conductor.manager [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b]   File "/usr/lib/python2.7/dist-packages/oslo_config/cfg.py", line 2519, in __getattr__
2018-03-19 10:08:44.672 61197 ERROR nova.conductor.manager [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b]     raise NoSuchOptError(name)
2018-03-19 10:08:44.672 61197 ERROR nova.conductor.manager [instance: 9b8767b2-80ed-4f8b-b99c-a5f72bb0a37b] NoSuchOptError: no such option keystone_authtoken in group [DEFAULT]

**Comment by sabbio93** [comment]
risolto cambiando il mapping della tastiera in us-eu
